export const DEBUG = false;
export const DEFAULTVOLUME = 0;
export const NOISE_BACKGROUND = `
  data:image/png;base64,
  iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAn8CBG0xnoYAAAAASUVORK5CYII=
`;
