name: Main Build, Test and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Modules
        run: yarn install

      - name: Run Build
        run: yarn run build

      - name: Run Tests
        run: yarn test

      - name: Create wwwroot structure
        run: |
          mkdir -p wwwroot
          cp -R .next/standalone/steffm4/steffm4/.next wwwroot/
          cp -R .next/standalone/steffm4/steffm4/db wwwroot/
          cp -R .next/standalone/steffm4/steffm4/node_modules wwwroot/
          cp .next/standalone/steffm4/steffm4/package.json wwwroot/
          cp -R .next/standalone/steffm4/steffm4/pages wwwroot/
          cp -R .next/standalone/steffm4/steffm4/public wwwroot/
          cp .next/standalone/steffm4/steffm4/server.js wwwroot/

      - name: Zip wwwroot
        run: zip -r wwwroot.zip wwwroot

      - name: Upload Zipped wwwroot
        uses: actions/upload-artifact@v4
        with:
          name: wwwroot
          path: wwwroot.zip

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Download Zipped wwwroot
        uses: actions/download-artifact@v4
        with:
          name: wwwroot
          path: .

      - name: Unzip wwwroot
        run: unzip wwwroot.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Key Vault Secrets
        id: keyvault
        run: |
          echo "NEXT_PUBLIC_DISCOGS_API_TOKEN=$(az keyvault secret show --name NEXTPUBLICDISCOGSAPITOKEN --vault-name stef-fm-secrets --query value -o tsv)" >> $GITHUB_ENV
          echo "JWT_SECRET=$(az keyvault secret show --name JWTSECRET --vault-name stef-fm-secrets --query value -o tsv)" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_API_URL=$(az keyvault secret show --name NEXTPUBLICAPIURL --vault-name stef-fm-secrets --query value -o tsv)" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "steffm"
          publish-profile: ${{ secrets.STEFFM_PUBLISH_PROFILE }}
          package: wwwroot

      - name: Set environment variables for Node.js
        run: |
          az webapp config appsettings set --name "steffm" --resource-group "Stef.FM" --settings NEXT_PUBLIC_DISCOGS_API_TOKEN=${{ env.NEXT_PUBLIC_DISCOGS_API_TOKEN }} JWT_SECRET=${{ env.JWT_SECRET }} NEXT_PUBLIC_API_URL=${{ env.NEXT_PUBLIC_API_URL }}

      - name: Clean up wwwroot.zip
        uses: geekyeggo/delete-artifact@v5
        with:
          name: wwwroot
          failOnError: false
