name: Main Build, Test and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Modules
        run: yarn install

      - name: Run Build
        run: yarn run build

      - name: Run Tests
        run: yarn test

      - name: Create wwwroot structure
        run: |
          mkdir -p wwwroot
          cp -R .next/standalone/steffm4/steffm4/.next wwwroot/
          cp -R .next/standalone/steffm4/steffm4/db wwwroot/
          cp -R .next/standalone/steffm4/steffm4/node_modules wwwroot/
          cp .next/standalone/steffm4/steffm4/package.json wwwroot/
          cp -R .next/standalone/steffm4/steffm4/pages wwwroot/
          cp -R .next/standalone/steffm4/steffm4/public wwwroot/
          cp .next/standalone/steffm4/steffm4/server.js wwwroot/

      - name: Zip wwwroot
        run: zip -r wwwroot.zip wwwroot

      - name: Upload Zipped wwwroot
        uses: actions/upload-artifact@v2
        with:
          name: wwwroot
          path: wwwroot.zip

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Download Zipped wwwroot
        uses: actions/download-artifact@v2
        with:
          name: wwwroot
          path: .

      - name: Unzip wwwroot
        run: unzip wwwroot.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "steffm"
          publish-profile: ${{ secrets.STEFFM_PUBLISH_PROFILE }}
          package: wwwroot
